nadia added wc.py, ls_beau.py, ls_pipe.py, sort.py, rm.py, cat.py
pavlovanadia/Python_BI_2022 pull request #8
Opened 2022-12-10 20:55 UTC by pavlovanadia

Homework 8 dedicated to the UNIX tools

2022-12-15 22:53 UTC, pavlovanadia commented
https://music.youtube.com/playlist?list=OLAK5uy_notC5aAGDVPDXNPwEdmKUHNwZaQoDdu4k

2022-12-22 00:48 UTC, krglkvrmn requested changes
![image](https://user-images.githubusercontent.com/48160953/209030892-8900b490-1e0d-46c2-9e85-2ad8df0d6066.png)

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/cat.py
> +            for line in inp.readlines():
```suggestion
            for line in inp:
```

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/cat.py
> +#! /usr/bin/env python3
Верно, только без пробела
```suggestion
#!/usr/bin/env python3
```

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/grep.py
> +pattern = re.compile(args.regex)
Мудрое решение

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/grep.py
> +    file = open(args.files[0], 'r')
А закрывать кто будет?

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/grep.py
> +                sys.stdout.write(f'{document}:{line}')
В  зависимости от того, сколько у нас файлов меняется только эта строка, остальной код одинаковый. Особо не было смысла его копировать в обе ветки

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/ls_beau.py
> +term_size = os.get_terminal_size().columns
![image](https://user-images.githubusercontent.com/48160953/209027672-1c1158a8-04f9-4ede-912c-334fb7c814a4.png)

Жалко только, что код перегружен и плохо читается

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/sort.py
> +            for line in inp.readlines():
```suggestion
            for line in inp:
```

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/sort.py
> +for line in sorted(sorted(all_lines), key=lambda x: x.lstrip("_").lower()):
1. Зачем такая странная сортировка внутри
2. Наружная сортировка всё равно в итоге сделает всё по своему, поэтому она особо смысла не имеет

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/tail.py
> +parser.add_argument('files', nargs='*', default=sys.stdin)
Что-то не работает в пайпе
![image](https://user-images.githubusercontent.com/48160953/209029148-5e5a388d-8dd4-412d-ac49-c94b6bc7e303.png)

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/tail.py
> +parser.add_argument('files', nargs='*', default=sys.stdin)
Видимо, из-за того, что дефолтное значение - stdin, а у него нет длины

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/tail.py
> +        output.append(line)
Да это же очередь

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/tail.py
> +            sys.stdout.write('\n')
Опять же, отличия в двух ветках условия - минимальные

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/wc.py
> +parser.add_argument("-l", "--lines", action="store_true")
Не сходится число строк
![image](https://user-images.githubusercontent.com/48160953/209029679-2e327c27-4245-41e5-b0a4-39157410f5ba.png)

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/wc.py
> +if args.lines == args.words == args.bytes == False:
```suggestion
if not any(vals):
```

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/wc.py
> +    vals[2] = True
```suggestion
else:
    vals = [args.lines, args.words, args.bytes]
```

2022-12-22 00:48 UTC, krglkvrmn commented on homework_8/wc.py
> +        print(f'      {"       ".join(map(str, ans))}')
Очень переусложнено

2023-07-05 20:05 UTC, merged